version: "2"

services:

  db:
    image: mysql:5.6.33
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build:
      context: app
      # comment out 2 following lines for team edition
      args:
        - edition=team
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      MM_SQLSETTINGS_DRIVERNAME: mysql
      MM_SQLSETTINGS_DATASOURCE: "mmuser:mmuser_password@tcp(db:3306)/mattermost_dev?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"
      DB_PORT_NUMBER: 3306
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      # This directory must have cert files
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
